# Configure repos
- name: Configure YUM repositories
  when: ansible_facts.pkg_mgr in ["yum", "dnf", "dnf5"]
  become: true
  yum_repository: "{{ item }}"
  loop: "{{ system_packages_yum_repositories }}"
  loop_control:
    label: "{{ item.name }}"

# Configure packages
- name: Manage system packages using dnf
  when: ansible_facts.pkg_mgr in ["dnf", "dnf5"]
  become: true
  package: "{{ item }}"
  loop: "{{ system_packages_dnf }}"
