# Common workstation - A machine that does not need anything special or custom.

# System packages
system_packages_yum_repositories:
  - name: keybase
    description: Keybase - $basearch
    baseurl: http://prerelease.keybase.io/rpm/$basearch
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
    gpgcheck: true
    metadata_expire: 60

system_packages_copr_repositories:
  - name: lihaohong/chezmoi # Using COPR because chezmoi does not (yet?) provide a simple alternative for Fedora users https://github.com/twpayne/chezmoi/issues/1800

system_packages_dnf:
  - name:
      - nano
      - nano-default-editor # Remove nano as default editor
    state: absent

  - name:
      - keybase # Tool to store and retrieve GPG key(s)
      - adobe-source-code-pro-fonts # Font for source code that seems readable and appealing
      - chezmoi # Managing dotfiles - https://github.com/idelsink/dotfiles
      - powerline-go # Shell prompt of choice
      - tmux # Terminal multiplexer of choice
      - vim # Used as basic editor)
      - vim-default-editor # Set vim as default editor (in combination with nano being removed)
    state: present

flatpak_remotes:
  - name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  - name:
      - com.spotify.Client
      - com.discordapp.Discord
      - org.telegram.desktop
      - org.gnome.Extensions # Simple tool to quickly access Gnome extension Settings
    method: system
    remote: flathub
