# Common workstation - A machine that does not need anything special or custom.

# System packages
system_packages_copr_repositories:
  - name: lihaohong/chezmoi # Using COPR because chezmoi does not (yet?) provide a simple alternative for Fedora users https://github.com/twpayne/chezmoi/issues/1800

system_packages_dnf:
  # Remove nano as default editor
  - name:
      - nano
      - nano-default-editor
    state: absent

  - name:
      - adobe-source-code-pro-fonts # Font for source code that seems readable and appealing
      - chezmoi # Managing dotfiles - https://github.com/idelsink/dotfiles
      - powerline-go # Shell prompt of choice
      - tmux # Terminal multiplexer of choice
      - vim # Used as basic editor)
      - vim-default-editor # Set vim as default editor (in combination with nano being removed)
    state: present
