# Common workstation - A machine that does not need anything special or custom.

# System packages
system_packages_yum_repositories:
  # This repo is changed after installing keybase for the first time by keybase itself. It runs a
  # post-install script if /etc/default/keybase is not present, this then overwrites some values
  # in the repo file. This includes the name and baseurl (removing $basearch and replaceing it
  # with a constant arch) So if this is run again a second time, it will update the file again
  # once more, but only once. From that moment on it will not be updated unless the
  # /etc/default/keybase file is removed and the keybase package is reinstalled.
  # See also:
  # - https://github.com/keybase/client/blob/ab3b3ec82851e3604bfca5642b7fdb8a30a72232/packaging/linux/rpm/cron.template#L225
  # - https://github.com/keybase/client/issues/9756
  - name: keybase
    description: Keybase $releasever - $basearch
    baseurl: http://prerelease.keybase.io/rpm/$basearch
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc
    gpgcheck: true
    metadata_expire: 60
  # Terra repository
  # This is only used becaue zed is not yet available in the official Fedora repositories
  # https://github.com/zed-industries/zed/discussions/25635
  # Zed's offical suggestion is to use the terra repository
  - name: terra
    description: Terra $releasever - $basearch
    #baseurl=https://repos.fyralabs.com/terra$releasever
    metalink: https://tetsudou.fyralabs.com/metalink?repo=terra$releasever&arch=$basearch
    metadata_expire: "6h"
    gpgcheck: true
    gpgkey: https://repos.fyralabs.com/terra$releasever/key.asc
    repo_gpgcheck: true
    includepkgs:
      - zed

system_packages_copr_repositories:
  - name: lihaohong/chezmoi # Using COPR because chezmoi does not (yet?) provide a simple alternative for Fedora users https://github.com/twpayne/chezmoi/issues/1800

system_packages_dnf:
  - name:
      - nano
      - nano-default-editor # Remove nano as default editor
    state: absent

  - name:
      - adobe-source-code-pro-fonts # Font for source code that seems readable and appealing
      - chezmoi # Managing dotfiles - https://github.com/idelsink/dotfiles
      - crudini # Tool to manipulate ini files - Used for example by chezmoi to export and backup dconf settings
      - htop #
      - jq # CLI to manipulate json strings/files
      - keybase # Tool to store and retrieve GPG key(s)
      - powerline-go # Shell prompt of choice
      - shellcheck # ShellCheck used by code editors for static analysis
      - tmux # Terminal multiplexer of choice
      - vim # Used as basic editor)
      - vim-default-editor # Set vim as default editor (in combination with nano being removed)
      - zed # Zed text editor
    state: present

flatpak_remotes:
  - name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  - name: com.discordapp.Discord
  - name: com.spotify.Client
  - name: org.gnome.Extensions # Simple tool to quickly access Gnome extension Settings
  - name: org.telegram.desktop

gnome_extensions:
  - id: '0517' # Caffeine Disable the screensaver and auto suspend - https://extensions.gnome.org/extension/517/caffeine/
  - id: '0600' # Launch new instance - https://extensions.gnome.org/extension/600/launch-new-instance/
  - id: '0615' # AppIndicator and KStatusNotifierItem Support - https://extensions.gnome.org/extension/615/appindicator-support/
  - id: '1007' # Window Is Ready - Notification Remover - https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/
  - id: '1160' # Dash to Panel - https://extensions.gnome.org/extension/1160/dash-to-panel/
  - id: '1401' # Bluetooth quick connect - https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/
  - id: '2932' # Executor - https://extensions.gnome.org/extension/2932/executor/
  - id: '4105' # Notification Banner Position - https://extensions.gnome.org/extension/4105/notification-banner-position/
  - id: '6242' # Emoji Copy - https://extensions.gnome.org/extension/6242/emoji-copy/

  - id: '0006' # Applications Menu - https://extensions.gnome.org/extension/6/applications-menu/
    enabled: false
  - id: '0008' # Places Status Indicator - https://extensions.gnome.org/extension/8/places-status-indicator/
    enabled: false
  - id: '7364' # Background Logo - https://extensions.gnome.org/extension/7364/background-logo/
    enabled: false
